name: ci

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - package.json
      - app/**
      # start: e2e #
      - e2e/**
      # end: e2e #
      # start: docker #
      - Dockerfile
      # end: docker #
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - package.json
      - src/**
      # start: e2e #
      - e2e/**
      # end: e2e #
      # start: docker #
      - Dockerfile
      # end: docker #

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm lint
      - run: npx prettier --check . --experimental-cli
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm build

  unit-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm test
